In [2]:
import numpy as np

In [2]:
np.set_printoptions(precision=2)

**1**.

A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.

(Source: Project Euler Problem 4)

In [65]:
# Initialize largest palindrome
largest_pal = 0
large_i = 0
large_j = 0

# Loop through all possible combinations
for i in range(100, 1001):
    for j in range(100, 1001):
        product = i * j
        if str(product) == str(product)[::-1] and product > largest_pal:
            largest_pal = product
            large_i = i
            large_j = j

# Display result
print(str(large_i) + " * " + str(large_j) + " = " + str(largest_pal))

913 * 993 = 906609


In [11]:
# Nicer-looking solution that we went over in lecture
xs = np.arange(100, 1000)
ys = np.unique(np.outer(xs, xs)) # Outer product (every element of xs with every element of itself)
max([y for y in ys if str(y) == str(y)[::-1]])

906609

**2**.

Construc the following matrix

```python
array([[18, 13, 10,  9, 10, 13, 18],
       [13,  8,  5,  4,  5,  8, 13],
       [10,  5,  2,  1,  2,  5, 10],
       [ 9,  4,  1,  0,  1,  4,  9],
       [10,  5,  2,  1,  2,  5, 10],
       [13,  8,  5,  4,  5,  8, 13],
       [18, 13, 10,  9, 10, 13, 18]])
```

In [32]:
# Construct individual rows
row1_7 = np.array([18, 13, 10, 9, 10, 13, 18]).reshape(1, -1)
row2_6 = np.array([13, 8, 5, 4, 4, 8, 13]).reshape(1, -1)
row3_5 = np.array([10, 5, 2, 1, 2, 5, 10]).reshape(1, -1)
row4 = np.array([9, 4, 1, 0, 1, 4, 9]).reshape(1, -1)

# Perform row stacking
np.r_[row1_7, row2_6, row3_5, row4, row3_5, row2_6, row1_7]

array([[18, 13, 10,  9, 10, 13, 18],
       [13,  8,  5,  4,  4,  8, 13],
       [10,  5,  2,  1,  2,  5, 10],
       [ 9,  4,  1,  0,  1,  4,  9],
       [10,  5,  2,  1,  2,  5, 10],
       [13,  8,  5,  4,  4,  8, 13],
       [18, 13, 10,  9, 10, 13, 18]])

In [66]:
# From solutions (using np.fromfunction)
np.fromfunction(lambda i,j: (i-3)**2 + (j-3)**2, [7,7]).astype('int')

array([[18, 13, 10,  9, 10, 13, 18],
       [13,  8,  5,  4,  5,  8, 13],
       [10,  5,  2,  1,  2,  5, 10],
       [ 9,  4,  1,  0,  1,  4,  9],
       [10,  5,  2,  1,  2,  5, 10],
       [13,  8,  5,  4,  5,  8, 13],
       [18, 13, 10,  9, 10, 13, 18]])

**3**.

Using numpy and string manipulation, create a DNA string with 150 bases that have the following probabilities: (A, 0.5), (C, 0.2), (T, 0.2), (G, 0.1). Find the most common triplet of bases in among sliding windows of this DNA string. For example, a sliding window of size 3 for GATTACA would be GAT, ATT, TTA, TAC, ...

In [13]:
# Sample 150 bases with given probabilities
choices = np.array(["A", "C", "T", "G"])
probs = np.array([0.5, 0.2, 0.2, 0.1])
dna_array = np.random.choice(a = choices, size = 150, replace = True, p = probs)

# Create a single string out of the sampled bases
dna_string = "".join(list(dna_array))

# Find most common triplet
triplets_dict = {}
for index, base in enumerate(dna_string[:-2]):
    current_triplet = dna_string[index] + dna_string[index + 1] + dna_string[index + 2]
    triplets_dict[current_triplet] = triplets_dict.get(current_triplet, 0) + 1

# Display result
#print(triplets_dict)

# Display sorted results
print(sorted(triplets_dict.items(), key = lambda x: -x[1]))

[('AAA', 17), ('AAT', 10), ('CAA', 9), ('ATA', 9), ('TAA', 8), ('ACA', 7), ('AAC', 6), ('AGA', 5), ('GAA', 4), ('AAG', 4), ('TCA', 4), ('TTA', 4), ('ACC', 4), ('TAC', 4), ('ATT', 3), ('TAT', 3), ('CCA', 3), ('ATC', 3), ('CGG', 2), ('GGA', 2), ('AGC', 2), ('CCT', 2), ('CTA', 2), ('CAC', 2), ('ACG', 2), ('CGT', 2), ('GTA', 2), ('TAG', 2), ('GAC', 2), ('CAG', 2), ('GAT', 2), ('GGC', 1), ('GCG', 1), ('GCC', 1), ('GTC', 1), ('CTT', 1), ('GCT', 1), ('CTC', 1), ('ACT', 1), ('AGT', 1), ('ATG', 1), ('TGG', 1), ('CCG', 1), ('CGA', 1), ('CAT', 1), ('TCC', 1)]


In [68]:
# Solutions suggest using collection to determine most common triplet
from collections import Counter
Counter(triplets_dict).most_common(1)

[('AAA', 19)]

In [ ]:
# Full solution provided, which leverages lambda function
dna = np.random.choice(list('ACTG'), size=150, p=[0.5,0.2,0.2,0.1]) 
# Create triplets by column joins, using smart offsets. ''.join() takes the triplets (which are lists of 3) and makes 1 string
triplets = list(map(lambda x: ''.join(x), np.c_[dna[:-2], dna[1:-1], dna[2:]])) 
Counter(triplets).most_common(1)

**4**.

- Using only base Python and numpy, create a pairwise distance matrix of the two sets of *row* vectors given
- Scale the distances so that each *row* has mean zero and standard deviation 1

Use Euclidean distance.

In [16]:
np.random.seed(123)
xs = np.random.randint(1,10, (10, 5))
ys = np.random.randint(1,10, (8, 5))

In [81]:
# Calculate result without centering and scaling
result = np.zeros(shape = (10, 8))
for index_x, rowx in enumerate(xs):
    for index_y, rowy in enumerate(ys):
        result[index_x, index_y] = (sum((rowx - rowy) ** 2)) ** 0.5

        
# Calculate row means, and subtract from each row
row_means = np.mean(result, axis = 1).reshape(10, -1)
row_sd = np.std(result, axis = 1).reshape(10, -1)
scaled_result = (result - row_means) / row_sd
print(scaled_result)

#np.mean(result, axis = 1)[:, None] is another option for broadcasting

[[ 1.57 -1.77 -0.32 -0.12  0.33  1.16  0.06 -0.9 ]
 [ 0.64  0.44 -0.71 -0.62 -0.59  1.88  0.5  -1.55]
 [ 1.42 -0.97 -0.8   0.64  0.07  1.23 -0.02 -1.57]
 [ 1.73 -1.18 -0.45 -1.18  0.61  1.18 -0.29 -0.41]
 [-1.9   0.79  1.11  0.79 -0.92 -0.78  0.31  0.59]
 [-0.63  0.26  0.66  2.06 -0.92 -1.35 -0.35  0.26]
 [ 1.64 -1.52 -0.15  0.94  0.07  0.75 -0.74 -1.  ]
 [ 0.79 -0.37  0.79 -1.81 -0.48  1.51  0.41 -0.83]
 [-0.78  0.75  0.91 -2.16 -0.51  0.58  0.58  0.64]
 [ 0.9  -1.04 -0.39 -1.99  1.02  0.27  0.4   0.84]]


In [17]:
# Refresher on einstein notation for matrix product (not related to exercise)
np.einsum('ik, jk -> ij', xs, ys)

array([[103, 103,  56, 106,  87, 132, 104,  63],
       [ 87,  47,  35,  86,  73,  76,  65,  47],
       [ 63,  73,  37,  60,  61,  90,  76,  47],
       [115, 114,  73, 133,  98, 147, 124,  73],
       [207, 119,  77, 138, 159, 216, 150,  91],
       [165, 110,  71, 101, 130, 193, 137,  77],
       [110, 111,  64,  99, 101, 149, 124,  74],
       [137, 112,  59, 147, 120, 143, 119,  85],
       [169, 112,  77, 152, 129, 179, 133,  80],
       [144, 114,  76, 139, 105, 170, 123,  67]])