In [1]:
import numpy as np

In [2]:
np.set_printoptions(precision=2)

**1**.

A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.

(Source: Project Euler Problem 4)

In [65]:
# Initialize largest palindrome
largest_pal = 0
large_i = 0
large_j = 0

# Loop through all possible combinations
for i in range(100, 1001):
    for j in range(100, 1001):
        product = i * j
        if str(product) == str(product)[::-1] and product > largest_pal:
            largest_pal = product
            large_i = i
            large_j = j

# Display result
print(str(large_i) + " * " + str(large_j) + " = " + str(largest_pal))

913 * 993 = 906609


**2**.

Construc the following matrix

```python
array([[18, 13, 10,  9, 10, 13, 18],
       [13,  8,  5,  4,  5,  8, 13],
       [10,  5,  2,  1,  2,  5, 10],
       [ 9,  4,  1,  0,  1,  4,  9],
       [10,  5,  2,  1,  2,  5, 10],
       [13,  8,  5,  4,  5,  8, 13],
       [18, 13, 10,  9, 10, 13, 18]])
```

In [32]:
# Construct individual rows
row1_7 = np.array([18, 13, 10, 9, 10, 13, 18]).reshape(1, -1)
row2_6 = np.array([13, 8, 5, 4, 4, 8, 13]).reshape(1, -1)
row3_5 = np.array([10, 5, 2, 1, 2, 5, 10]).reshape(1, -1)
row4 = np.array([9, 4, 1, 0, 1, 4, 9]).reshape(1, -1)

# Perform row stacking
np.r_[row1_7, row2_6, row3_5, row4, row3_5, row2_6, row1_7]

array([[18, 13, 10,  9, 10, 13, 18],
       [13,  8,  5,  4,  4,  8, 13],
       [10,  5,  2,  1,  2,  5, 10],
       [ 9,  4,  1,  0,  1,  4,  9],
       [10,  5,  2,  1,  2,  5, 10],
       [13,  8,  5,  4,  4,  8, 13],
       [18, 13, 10,  9, 10, 13, 18]])

In [66]:
# From solutions (using np.fromfunction)
np.fromfunction(lambda i,j: (i-3)**2 + (j-3)**2, [7,7]).astype('int')

array([[18, 13, 10,  9, 10, 13, 18],
       [13,  8,  5,  4,  5,  8, 13],
       [10,  5,  2,  1,  2,  5, 10],
       [ 9,  4,  1,  0,  1,  4,  9],
       [10,  5,  2,  1,  2,  5, 10],
       [13,  8,  5,  4,  5,  8, 13],
       [18, 13, 10,  9, 10, 13, 18]])

**3**.

Using numpy and string manipulation, create a DNA string with 150 bases that have the following probabilities: (A, 0.5), (C, 0.2), (T, 0.2), (G, 0.1). Find the most common triplet of bases in among sliding windows of this DNA string. For example, a sliding window of size 3 for GATTACA would be GAT, ATT, TTA, TAC, ...

In [67]:
# Sample 150 bases with given probabilities
choices = np.array(["A", "C", "T", "G"])
probs = np.array([0.5, 0.2, 0.2, 0.1])
dna_array = np.random.choice(a = choices, size = 150, replace = True, p = probs)

# Create a single string out of the sampled bases
dna_string = "".join(list(dna_array))

# Find most common triplet
triplets_dict = {}
for index, base in enumerate(dna_string[:-2]):
    current_triplet = dna_string[index] + dna_string[index + 1] + dna_string[index + 2]
    triplets_dict[current_triplet] = triplets_dict.get(current_triplet, 0) + 1

# Display result
#print(triplets_dict)

# Display sorted results
print(sorted(triplets_dict.items(), key = lambda x: -x[1]))

[('AAA', 19), ('ACA', 12), ('AAC', 12), ('ATA', 8), ('GAA', 7), ('CAA', 7), ('CAT', 6), ('AAT', 6), ('TAA', 6), ('CAC', 6), ('TCA', 5), ('CGA', 4), ('ACT', 4), ('CTC', 4), ('ACC', 3), ('ATC', 3), ('TAC', 2), ('ACG', 2), ('ATT', 2), ('TTA', 2), ('CCA', 2), ('TAT', 2), ('TCC', 2), ('CCT', 2), ('AGA', 2), ('ATG', 2), ('TGA', 2), ('TCG', 2), ('AAG', 2), ('CTT', 1), ('CAG', 1), ('AGC', 1), ('GCA', 1), ('CTA', 1), ('TAG', 1), ('GAT', 1), ('TTC', 1), ('AGT', 1), ('GTC', 1)]


In [68]:
# Solutions suggest using collection to determine most common triplet
from collections import Counter
Counter(triplets_dict).most_common(1)

[('AAA', 19)]

In [ ]:
# Full solution provided, which leverages lambda function
dna = np.random.choice(list('ACTG'), size=150, p=[0.5,0.2,0.2,0.1])
triplets = list(map(lambda x: ''.join(x), np.c_[dna[:-2], dna[1:-1], dna[2:]]))
Counter(triplets).most_common(1)

**4**.

- Using only base Python and numpy, create a pairwise distance matrix of the two sets of *row* vectors given
- Scale the distances so that each *row* has mean zero and standard deviation 1

Use Euclidean distance.

In [61]:
np.random.seed(123)
xs = np.random.randint(1,10, (10, 5))
ys = np.random.randint(1,10, (8, 5))

In [81]:
# Calculate result without centering and scaling
result = np.zeros(shape = (10, 8))
for index_x, rowx in enumerate(xs):
    for index_y, rowy in enumerate(ys):
        #result[index_x, index_y] = np.dot(rowx, rowy) ** 0.5
        result[index_x, index_y] = (sum((rowx - rowy) ** 2)) ** 0.5

        
# Calculate row means, and subtract from each row
row_means = np.mean(result, axis = 1).reshape(10, -1)
row_sd = np.std(result, axis = 1).reshape(10, -1)
scaled_result = (result - row_means) / row_sd
print(scaled_result)

[[ 1.57 -1.77 -0.32 -0.12  0.33  1.16  0.06 -0.9 ]
 [ 0.64  0.44 -0.71 -0.62 -0.59  1.88  0.5  -1.55]
 [ 1.42 -0.97 -0.8   0.64  0.07  1.23 -0.02 -1.57]
 [ 1.73 -1.18 -0.45 -1.18  0.61  1.18 -0.29 -0.41]
 [-1.9   0.79  1.11  0.79 -0.92 -0.78  0.31  0.59]
 [-0.63  0.26  0.66  2.06 -0.92 -1.35 -0.35  0.26]
 [ 1.64 -1.52 -0.15  0.94  0.07  0.75 -0.74 -1.  ]
 [ 0.79 -0.37  0.79 -1.81 -0.48  1.51  0.41 -0.83]
 [-0.78  0.75  0.91 -2.16 -0.51  0.58  0.58  0.64]
 [ 0.9  -1.04 -0.39 -1.99  1.02  0.27  0.4   0.84]]
